rabbitmq:
  container_name: rabbitmq
  image: daocloud.io/library/rabbitmq:3.6.5-management
  ports:
   - "15672:15672"
   - "5672:5672"
  environment:
      RABBITMQ_ERLANG_COOKIE: TOOHKEZEVYNWGFRYBBYD
  volumes:
    - /data/docker/rabbitmq/rabbitmq/mnesia/:/var/lib/rabbitmq/mnesia/
    - /data/docker/rabbitmq/rabbitmq/backup/:/backup
  # restart: always
