mongodb:
  container_name: mongodb
  image: daocloud.io/library/mongo:3.4.2
  ports:
   - "27017:27017"
  volumes:
    - /data/docker/mongodb/data:/data/db
    - /data/docker/mongodb/logs/:/var/log/mongodb/
    - /data/docker/mongodb/backup/:/backup/
