superset:
  container_name: superset
  image: daocloud.io/gizwits2015/superset
  environment:
   - SQLALCHEMY_DATABASE_URI=mysql://root:root@172.16.10.252/superset?charset=utf8
  ports:
   - "80:8088"
  expose:
   - "80"
  command: "superset runserver"
