redis:
  container_name: redis
  image: daocloud.io/library/redis:3
  ports:
   - "6379:6379"
  expose:
   - "6379"
  environment:
  - REDIS_PASS=**None**
  # volumes:
    # - ./redis/data:/data/
  # command: redis-server --requirepass Go4gizwits
  # command: redis-server --appendonly yes --requirepass Go4gizwits
